/*
 * Spot, created by Justin Lee, Oliver Pang, Quyen Tran, Shuyang Wang for HackUMass V
 */

package idc.searchparty2;

import android.content.Intent;
import android.support.v7.app.ActionBar;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;

/**
 *  The main class of the program. It is a standard MainActivity class automatically generated by
 *  Android Studio and is executed when the application is launched on the target device or virtual
 *  device.
 */
public class MainActivity extends AppCompatActivity {

    /**
     *  <code> onCreate </code> method of the MainActivity class. Initializes the main landing
     *  screen of the application, hides the action bar up top and initializes the .xml file
     *  containing the formatting for the landing screen.
     *
     * @param savedInstanceState    Default argument passed into the <code> onCreate() </code>
     *                              method. Used to restore the object to a previous state using
     *                              the data in the <code> Bundle </code> object.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ActionBar actionBar = getSupportActionBar();
        actionBar.hide();
        setContentView(R.layout.activity_main);
    }

    /**
     *  This method is executed when the Create Button is pressed on the landing page. A new Intent
     *  is created and the class file of the target <code> CreateSearch </code> class is passed into
     *  the constructor of the Intent object and the new activity is started.
     *
     * @param view  Default argument passed into the <code> createButtonPress </code> and specifies
     *              the current display viewed by the user.
     */
    public void createButtonPress(View view){
        Intent intent = new Intent(this, CreateSearch.class);
        startActivity(intent);
    }

    /**
     *  This method is executed when the Join Button is pressed on the landing page. A new Intent
     *  is created and the class file of the target <code> JoinSearch </code> class is passed into
     *  the constructor of the Intent object and the new activity is started.
     *
     * @param view  Default argument passed into the <code> createButtonPress </code> and specifies
     *              the current display viewed by the user.
     */
    public void joinButtonPress(View view){
        Intent intent = new Intent(this, JoinSearch.class);
        startActivity(intent);
    }

    /**
     *  This method is executed when the small Help Button is pressed on the bottom right of the
     *  landing page. A new Intent is created and the class file of the target
     *  <code> Help Screen </code> class is passed into the constructor of the Intent object and
     *  the new activity is started.
     *
     * @param view  Default argument passed into the <code> createButtonPress </code> and specifies
     *              the current display viewed by the user.
     */
    public void initiateHelp(View view){
        Intent intent = new Intent(this, HelpScreen.class);
        startActivity(intent);
    }
}
